# Generated by Django 5.2.3 on 2025-12-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Premium', 'No Flaws'), ('Good', 'Minor Wear'), ('Thrift', 'Has Flaws (Mystery Box)')], default='Premium', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='condition_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
